### ISSUE TITLE
Error: Please provide a valid Mongo connection uri

### ISSUE THREAD

**Issue by Inoir** [prisma/Mongo-Connector-Preview#9]
Prisma version: 1.22.0-alpha.158

Tried to setup new mongo connector on local docker image. 
Nothing changed after running "prisma init".

MongoDB instance is running, prisma instance keeps trying to restart, cause of invalid(?) prisma config.

Output of first initial command:

```
 $ db prisma init
 ? Set up a new Prisma server or deploy to an existing server? Create new database
 ? What kind of database do you want to deploy to? MongoDB
 ? Select the programming language for the generated Prisma client Prisma TypeScript Client
 
 Created 3 new files:
 
   prisma.yml           Prisma service definition
   datamodel.prisma    GraphQL SDL-based datamodel (foundation for database)
   docker-compose.yml   Docker configuration file
 
 Next steps:
 
   1. Start your Prisma server: docker-compose up -d
   2. Deploy your Prisma service: prisma deploy
   3. Read more about Prisma server:
      http://bit.ly/prisma-server-overview
 
 Generating schema... 20ms
 
 Saving Prisma Client (TypeScript) at /Users/*/Documents/Workspace/i18n-mono/packages/i18n-backend-graphql/src/graphql/db/generated/prisma-client/
 
 $ db docker-compose up -d
 Creating db_prisma_1_b9bfd469ca2a ... done
 Creating db_mongo_1_b3d50e08daaf  ... done
 $ db prisma deploy
  ▸    Could not connect to server at http://localhost:4466. Please check if your server is running.

 Get in touch if you need help: https://www.prisma.io/forum/
 To get more detailed output, run $ export DEBUG="*"
```

Error output from prisma docker container:

```
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: java.lang.RuntimeException: Please provide a valid Mongo connection uri.
at scala.sys.package$.error(package.scala:27)
at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:40)
at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:37)
at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:11)
at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:8)
at scala.Function0.apply$mcV$sp(Function0.scala:34)
at scala.Function0.apply$mcV$sp$(Function0.scala:34)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
at scala.App.$anonfun$main$1$adapted(App.scala:76)
at scala.collection.immutable.List.foreach(List.scala:389)
at scala.App.main(App.scala:76)
at scala.App.main$(App.scala:74)
at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:8)
at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala)
```

**Comment by krishnakprakash** [comment]
I am also facing the same issue. On investigating it further, found that the below issue was stoping the mongo instance, 

mongo_1   | 2018-11-23T07:23:34.125+0000 E -        [main] Error saving history file: FileOpenFailed: Unable to open() file /home/mongodb/.dbshell: No such file or directory
mongo_1   | 2018-11-23T07:23:34.127+0000 I NETWORK  [conn2] end connection 127.0.0.1:38828 (0 connections now open)

Is it the exact cause of the issue.

@Inoir can you please double check on this and let me know is this the same error which is the stopping your mongo service.

**Comment by Inoir** [comment]
@krishnakprakash ive same error message, but the mongo instance seems to restart without any errors right after.

`
[main] Error saving history file: FileOpenFailed: Unable to open() file /home/mongodb/.dbshell: No such file or directory
[...]
[initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=cedbc465237c
[...]
[initandlisten] waiting for connections on port 27017
[...]
`

striped few logs out, to see the restarting.

**Comment by do4gr** [comment]
Hey, we updated the way how to connect to the Mongo db. You now need to provide an uri. There are also now actual docs for Mongo. You can find them here. 

I'll update the documentation in this repo with a link to the actual documentation now. Sorry for the confusion!

**Comment by krishnakprakash** [comment]
The prisma config holds old env variables and once i change it as per the prisma config provided in docs, everything worked like charm.

Anyhow thank you very much @do4gr @Inoir

**Comment by do4gr** [comment]
We'll update the CLI today to generate the correct config, that was an oversight on our side. Thanks for bringing it up!
